# Generated by Django 2.2 on 2020-03-29 10:07

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_task_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=django_fsm.FSMIntegerField(choices=[(10, 'New'), (20, 'Active'), (50, 'Closed'), (30, 'Resolved')], default=10, protected=True),
        ),
    ]
