# Generated by Django 2.2 on 2020-07-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_remove_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='decline_comment',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
