# Generated by Django 2.2 on 2020-09-26 05:23

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_task_decline_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('status', django_fsm.FSMField(choices=[('created', 'Created'), ('cancelled', 'Cancelled'), ('paid', 'Paid'), ('delivered', 'Delivered')], default='created', max_length=50, protected=True)),
                ('payment_info', models.CharField(blank=True, max_length=100)),
                ('cancel_comment', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
