# Generated by Django 2.2 on 2020-10-11 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20201011_0953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='id',
            new_name='guid',
        ),
    ]
